name: build

on: [push]

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - uses: actions/cache@v2
        with:
          path: "bin/**/libInstrumentationEngine.*"
          key: ${{ github.workflow }}-clrie-${{ matrix.os }}-${{ hashFiles('scripts/get-clrie.sh') }}

      - name: build
        run: ./scripts/build.sh

      - name: test
        run: ./scripts/test.sh

      - name: archive so
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: libappmap-instrumentation.so
          path: build/libappmap-instrumentation.so

      - name: archive dylib
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v2
        with:
          name: libappmap-instrumentation.dylib
          path: build/libappmap-instrumentation.dylib
